# We have 2 stage Test and Deploy
stages:
  - build

# Config cache
cache:
  paths:
    - node_modules/

# Deploy job
deploy:
  tags:
    - shell
  # Attach Deploy job to Deploy stage
  stage: build
  script:
    # Only copy changed files to project folder
    - echo 'Update repo'
    - sudo rm -rf /var/www/azu/frontend/build
    - sudo cp -r -u * /var/www/azu/frontend/
    # - echo 'Install Packages'
    # - sudo flutter clean
    # - flutter packages get
    # - flutter packages upgrade
    # - echo 'Build App'
    # - sudo flutter build web --no-sound-null-safety
  only:
    - Mainnet
